package config

import (
	"os"
	"path/filepath"
	"testing"
)

// The master key lives in a file only the service used to read. Every command
// that opens the database failed on a key that was sitting right there.
func TestLoadEnvFileReadsTheKey(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".env")

	os.WriteFile(path, []byte(`# Generated by install.sh
REVPD_MASTER_KEY=abc123
REVPD_DUO_IKEY="quoted"
export REVPD_DUO_SKEY='single'

not-a-line
`), 0o600)

	t.Setenv("REVPD_MASTER_KEY", "")
	os.Unsetenv("REVPD_MASTER_KEY")

	if err := LoadEnvFile(path); err != nil {
		t.Fatal(err)
	}
	if got := os.Getenv("REVPD_MASTER_KEY"); got != "abc123" {
		t.Errorf("master key = %q", got)
	}
	if got := os.Getenv("REVPD_DUO_IKEY"); got != "quoted" {
		t.Errorf("quotes were not stripped: %q", got)
	}
	if got := os.Getenv("REVPD_DUO_SKEY"); got != "single" {
		t.Errorf("export prefix or quotes not handled: %q", got)
	}
}

// An explicitly exported value beats the file: somebody who set it meant it,
// and a file silently overriding that is an afternoon lost.
func TestEnvFileDoesNotOverrideTheEnvironment(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".env")
	os.WriteFile(path, []byte("REVPD_MASTER_KEY=from-file\n"), 0o600)

	t.Setenv("REVPD_MASTER_KEY", "from-environment")

	if err := LoadEnvFile(path); err != nil {
		t.Fatal(err)
	}
	if got := os.Getenv("REVPD_MASTER_KEY"); got != "from-environment" {
		t.Errorf("the file overrode an explicit value: %q", got)
	}
}

// Docker passes the key in the environment and ships no .env at all.
func TestMissingEnvFileIsNotAnError(t *testing.T) {
	if err := LoadEnvFile(filepath.Join(t.TempDir(), "nothing-here")); err != nil {
		t.Fatalf("a missing file was treated as a failure: %v", err)
	}
}

// It has to be the file the installer writes and the unit file reads.
func TestEnvFilePathSitsBesideTheConfig(t *testing.T) {
	if got := EnvFilePath("/etc/revpd/revpd.yaml"); got != "/etc/revpd/.env" {
		t.Errorf("EnvFilePath = %q, want /etc/revpd/.env", got)
	}
}

func TestParseEnvLine(t *testing.T) {
	cases := []struct {
		in, key, value string
		ok             bool
	}{
		{"A=b", "A", "b", true},
		{"  A = b  ", "A", "b", true},
		{"export A=b", "A", "b", true},
		{`A="b c"`, "A", "b c", true},
		{"A=", "A", "", true},
		{"# comment", "", "", false},
		{"", "", "", false},
		{"no-equals", "", "", false},
		{"=novalue", "", "", false},
	}
	for _, c := range cases {
		k, v, ok := parseEnvLine(c.in)
		if ok != c.ok || k != c.key || v != c.value {
			t.Errorf("parseEnvLine(%q) = (%q, %q, %v), want (%q, %q, %v)", c.in, k, v, ok, c.key, c.value, c.ok)
		}
	}
}
